version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: jwt-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: securitydb
      MYSQL_USER: user
      MYSQL_PASSWORD: 1107
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks: 
      - jwt-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: jwt-phpmyadmin
    restart: always
    environment:
      PMA_HOST: jwt-mysql
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - jwt-net
    ports:
      - "8081:80"

networks:
  jwt-net:
    driver: bridge
